openapi: "3.0.0"
info:
  title: "Messenger API"
  description: "Лабораторні роботи для курсу \"Проєктування та реалізація мікросервісної архітектури\". Береговий К.О., 3 курс "
  version: "1.0.0"
paths:
  /users/register:
    post:
      summary: "Реєстрація нового користувача"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: "Користувача успішно створено"
        '409':
          description: "Користувач з таким іменем або поштою вже існує"