ktor:
  application:
    modules:
      - com.example.MainKt.chatModule
  deployment:
    port: 8082
database:
  url: "jdbc:h2:mem:chatdb;DB_CLOSE_DELAY=-1"
  user: root
  password: ${DB_PASSWORD:} # Секрет, який Ktor підставить з середовища запуску Chat-сервісу